### ISSUE TITLE
No core class with name PcdCore found

### ISSUE THREAD

**Issue by Cheng909865905** [mihdalal/manipgen#15]
(manipgen-full) user@user-LZ880-GR:~/Desktop/disk_18T/user/code1/chk23/2025-4-5/manipgen$ python manipgen/real_world/scripts/run_manipgen.py --prompt "Put the corn in the black pot." --vlm_cam_idx 2

Traceback (most recent call last):
  File "manipgen/real_world/scripts/run_manipgen.py", line 91, in <module>
    motion_planner = NeuralMP(  # 初始化神经运动规划器
  File "/home/disk_18T/user/code1/chk23/2025-4-5/manipgen/manipgen/real_world/neural_mp.py", line 41, in __init__
    policy, _ = FileUtils.policy_from_checkpoint(
  File "/home/disk_18T/user/code1/chk23/2025-4-5/manipgen/robomimic/robomimic/utils/file_utils.py", line 386, in policy_from_checkpoint
    ObsUtils.initialize_obs_utils_with_config(config)
  File "/home/disk_18T/user/code1/chk23/2025-4-5/manipgen/robomimic/robomimic/utils/obs_utils.py", line 254, in initialize_obs_utils_with_config
    initialize_default_obs_encoder(obs_encoder_config=obs_encoder_config)
  File "/home/disk_18T/user/code1/chk23/2025-4-5/manipgen/robomimic/robomimic/utils/obs_utils.py", line 226, in initialize_default_obs_encoder
    DEFAULT_ENCODER_KWARGS = obs_encoder_kwargs_from_config(obs_encoder_config)
  File "/home/disk_18T/user/code1/chk23/2025-4-5/manipgen/robomimic/robomimic/utils/obs_utils.py", line 102, in obs_encoder_kwargs_from_config
    assert cfg_cls in cores, f"No {cls_name} class with name {cfg_cls} found, must register this class before" \
AssertionError: No core class with name PcdCore found, must register this class beforecreating model!

**Comment by minliu01** [comment]
Sorry this seems to be an issue related to branch of the submodules. I've fixed submodules with this issue and make sure they match the pre-release version.

**Comment by Cheng909865905** [comment]
Thank you for your patience, I tried to download your updated code, but I still get the following error！



Traceback (most recent call last):
  File "manipgen/real_world/scripts/run_manipgen.py", line 95, in <module>
    motion_planner = NeuralMP(  # 初始化神经运动规划器
  File "/home/user/Desktop/disk_18T/user/code1/chk23/2025-4-5/manipgen/manipgen/real_world/neural_mp.py", line 41, in __init__
    policy, _ = FileUtils.policy_from_checkpoint(
  File "/home/disk_18T/user/code1/chk23/2025-4-5/manipgen/robomimic/robomimic/utils/file_utils.py", line 394, in policy_from_checkpoint
    ObsUtils.initialize_obs_utils_with_config(config)
  File "/home/disk_18T/user/code1/chk23/2025-4-5/manipgen/robomimic/robomimic/utils/obs_utils.py", line 255, in initialize_obs_utils_with_config
    initialize_default_obs_encoder(obs_encoder_config=obs_encoder_config)
  File "/home/disk_18T/user/code1/chk23/2025-4-5/manipgen/robomimic/robomimic/utils/obs_utils.py", line 227, in initialize_default_obs_encoder
    DEFAULT_ENCODER_KWARGS = obs_encoder_kwargs_from_config(obs_encoder_config)
  File "/home/disk_18T/user/code1/chk23/2025-4-5/manipgen/robomimic/robomimic/utils/obs_utils.py", line 101, in obs_encoder_kwargs_from_config
    assert cfg_cls in cores, f"No {cls_name} class with name {cfg_cls} found, must register this class before" \
AssertionError: No core class with name PcdCore found, must register this class beforecreating model!

**Comment by Cheng909865905** [comment]
class PcdCore(EncoderCore, BaseNets.PointNetEncoder):
    """
    A network block that consists of a pcd backbone network.
    """
    def __init__(
        self,
        input_shape,
        backbone_class="PointNetEncoder",
        backbone_kwargs=None,
    ):
        """
        Args:
            input_shape (tuple): shape of input (not including batch dimension)
            backbone_class (str): class name for the pcd backbone network. Defaults to "PointNetEncoder".
            backbone_kwargs (dict): kwargs for the pcd backbone network (optional)
        """
        super(PcdCore, self).__init__(input_shape=input_shape)

        if backbone_kwargs is None:
            backbone_kwargs = dict()

        # visual backbone
        assert isinstance(backbone_class, str)
        self.backbone = eval(backbone_class)(**backbone_kwargs)

        net_list = [self.backbone]
        self.nets = nn.Sequential(*net_list)

    def output_shape(self, input_shape):
        """
        Function to compute output shape from inputs to this module. 

        Args:
            input_shape (iterable of int): shape of input. Does not include batch dimension.
                Some modules may not need this argument, if their output does not depend 
                on the size of the input, or if they assume fixed size input.

        Returns:
            out_shape ([int]): list of integers corresponding to output shape
        """
        return self.backbone.output_shape(input_shape)

    def forward(self, inputs):
        """
        Forward pass through visual core.
        """
        out = super(PcdCore, self).forward(inputs)
        return out

This problem is solved. obs_core.py script is modified as above by replacing all PCDCore in the original script with PcdCore
